// <auto-generated />
using System;
using Api.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace simpleApiWithAuth.Migrations
{
	[DbContext(typeof(PostgresApiContext))]
	[Migration("20220714135223_AddLookupTables")]
	partial class AddLookupTables
	{
		protected override void BuildTargetModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
					.HasAnnotation("ProductVersion", "6.0.7")
					.HasAnnotation("Relational:MaxIdentifierLength", 63);

			NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

			modelBuilder.Entity("Api.Entities.Product", b =>
					{
						b.Property<Guid>("Id")
											.ValueGeneratedOnAdd()
											.HasColumnType("uuid")
											.HasColumnName("id");

						b.Property<string>("Name")
											.IsRequired()
											.HasColumnType("text")
											.HasColumnName("name");

						b.Property<decimal>("Price")
											.HasColumnType("numeric")
											.HasColumnName("price");

						b.HasKey("Id")
											.HasName("pk_products");

						b.ToTable("products", (string)null);
					});

			modelBuilder.Entity("Api.Entities.User", b =>
					{
						b.Property<Guid>("Id")
											.ValueGeneratedOnAdd()
											.HasColumnType("uuid")
											.HasColumnName("id");

						b.Property<string>("Email")
											.IsRequired()
											.HasColumnType("text")
											.HasColumnName("email");

						b.Property<string>("FirstName")
											.IsRequired()
											.HasColumnType("text")
											.HasColumnName("first_name");

						b.Property<string>("LastName")
											.IsRequired()
											.HasColumnType("text")
											.HasColumnName("last_name");

						b.Property<string>("Password")
											.IsRequired()
											.HasColumnType("text")
											.HasColumnName("password");

						b.Property<string>("Role")
											.IsRequired()
											.HasColumnType("text")
											.HasColumnName("role");

						b.HasKey("Id")
											.HasName("pk_users");

						b.ToTable("users", (string)null);
					});
#pragma warning restore 612, 618
		}
	}
}
